name: build

on: [push]

jobs:
  Linux:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: cmake build
        run: mkdir build && cd build && cmake .. && make

      - name: example.c
        run: cd build && ./log_example

      - name: example.cpp
        run: cd build && ./log_example
