name: build

on: [push]

jobs:
  Linux:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: cmake build
        run: mkdir build && cd build && cmake .. && make && ./example
