name: macOS

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  macOS:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v3

      - name: cmake build
        run: mkdir build && cd build && cmake .. && make -j2

      - name: test
        run: |
          cd build
          ./log_example
          ./log_example_c
          ./log_example_disable_thread_safe
          ./log_example_disable_thread_id
          ./log_example_disable_date_time
          ./log_example_disable_ts_ti_dt
